# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-symlinks
    -   id: debug-statements

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8

-   repo: https://github.com/myint/rstcheck
    rev: 3f92957478422df87bd730abde66f089cc1ee19b
    hooks:
    -   id: rstcheck

-   repo: https://github.com/jazzband/pip-tools
    rev: 5.5.0
    hooks:
    -   id: pip-compile
        files: ^requirements.(in|txt)$

-   repo: https://github.com/sondrelg/pep585-upgrade
    rev: 927066c3913e49b22b265209f10a9210c4fa2af0
    hooks:
    -   id: upgrade-type-hints

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.0
    hooks:
    -   id: gitlint
        args: [--msg-filename]

-   repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
    -   id: codespell

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
    -   id: mypy
        entry: mypy --strict

-   repo: https://github.com/asottile/pyupgrade
    rev: v2.9.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        language: python
        entry: pytest
        pass_filenames: false
        always_run: true
