#!/usr/bin/env python
'''Print number of cards due.'''

from pathlib import Path
from argparse import ArgumentParser
import sqlite3
import os

if __name__ == '__main__':
    PARSER = ArgumentParser(description='Count number of cards due.')
    PARSER.add_argument('--day-offset', type=int, default=0,
                        help='cards due N days from today')
    PARSER.add_argument('--width', type=int, default=0,
                        help='provide count with minimum width')
    ARGS = PARSER.parse_args()

    CONFIG = os.environ['XDG_DATA_HOME']
    DB = Path(CONFIG, 'Anki2', 'User 1', 'collection.anki2')

    # type 0 is new cards
    # type 1 is learning cards
    # type 2 is repeated cards
    # due date is relative to collection creation date
    DUE_QUERY = '''
    WITH today(offset) AS (
        SELECT
            julianday(date('now', 'localtime'))
            - julianday(date(crt, 'unixepoch', 'localtime'))
        FROM col
    )
    SELECT COUNT(*) FROM cards
    WHERE
        queue == 0
        AND (
          type == 0
          OR (type == 1 AND due <= strftime('%s', 'now'))
          OR (type == 2 AND due <= (SELECT offset + ? FROM today))
        )
    ;
    '''

    with sqlite3.connect(str(DB), timeout=10) as conn:
        with conn as cur:
            (DUE,) = cur.execute(DUE_QUERY, (ARGS.day_offset,)).fetchone()

    print(str(DUE).rjust(ARGS.width))
