#!/bin/sh
if [ -f /home/jared/.Xresources ]; then
    xrdb -merge /home/jared/.Xresources
fi

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

setxkbmap -option caps:escape
feh --bg-scale "${XDG_CONFIG_HOME}/background.jpg"

xset r rate 200 30

exec i3
