env:
  es2021: true
extends:
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  project: "./tsconfig.eslint.json"
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "no-var": "error",
  "prefer-const": "error",
  "guard-for-in": "error",
  "no-restricted-globals": [
    "error",
    {
      "name": "isNaN",
      "message": "Use Number.isNaN instead"
    }
  ],
  "space-before-function-paren": ["error", "never"],
  "generator-star-spacing": ["error", {"before": false, "after": true}],
  "@typescript-eslint/return-await": ["error", "always"],
  "@typescript-eslint/strict-boolean-expressions": ["error", {
    allowString: false,
    allowNumber: false,
    allowNullableObject: false,
    allowNullableBoolean: false,
    allowNullableString: false,
    allowNullableNumber: false,
    allowAny: false
  }],
}
